#!/usr/bin/env bash
#Bash script that displays:
#The content of the current directory
#In a list format
#Where only the part of the name after the first dash is displayed

content=$(ls)
for files in $content
do
	name=$(echo $files | cut -f2 -d "-")
	echo "$name"
done
